/**
 * generated by Xtext
 */
package org.xtext.validation;

import org.xtext.validation.AbstractARMValidator;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class ARMValidator extends AbstractARMValidator {
}
