/*
 * generated by Xtext
 */
package org.xtext;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class ARMStandaloneSetup extends ARMStandaloneSetupGenerated{

	public static void doSetup() {
		new ARMStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

