/*
 * generated by Xtext
 */
package org.xtext.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtext.conversion.impl.STRINGValueConverter;
import org.eclipse.xtext.ui.editor.syntaxcoloring.DefaultHighlightingConfiguration;
import org.eclipse.xtext.ui.editor.syntaxcoloring.ISemanticHighlightingCalculator;

/**
 * Use this class to register components to be used within the IDE.
 */
public class ARMUiModule extends org.xtext.ui.AbstractARMUiModule {
	public ARMUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
	
	public Class<? extends DefaultHighlightingConfiguration>
	bindIHighlightingConfiguration(){
		return ARMHighlightingConfiguration.class;
	}
	
	public Class<? extends ISemanticHighlightingCalculator> 
	bindISemanticHighlightingCalculator(){
		return ARMHighlightingCalculator.class;
	}
	
	public Class<? extends STRINGValueConverter> 
	bindSTRINGValueConverter()
	{
		return converters.class;
	}

	@Override
    public Class<? extends org.eclipse.xtext.ui.editor.hover.IEObjectHover> bindIEObjectHover() {
        return ARMDispatchingEObjectTextHover.class;
    }
 
    public Class<? extends org.eclipse.xtext.ui.editor.hover.IEObjectHoverProvider> bindIEObjectHoverProvider() {
        return ARMHoverProvider.class;
    }
}
